### ISSUE TITLE
Please do not use stdatomic.h in C++ because it is not defined in C++

### ISSUE THREAD

**Issue by yurivict** [steinbergmedia/vst3_pluginterfaces#10]
[Here](https://github.com/steinbergmedia/vst3_pluginterfaces/blob/2ad397ade5b51007860bedb3b01b8afd2c5f6fba/base/funknown.cpp#L59)

**Comment by scheffle** [comment]
Please be more precise in your bug report: Describe the problem, state which compiler and operating system you use.

**Comment by yurivict** [comment]
Compiler is clang-13, OS is FreeBSD, but this doesn't matter. C++ doesn't define this header.

See the [downstream bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=262683).

**Comment by scheffle** [comment]
https://en.cppreference.com/w/cpp/header/stdatomic.h
Looks like it does. But it doesn't matter, as it's already fixed in the upcoming release.
