### ISSUE TITLE
IEventHandler::onFDIsSet interface can be improved

### ISSUE THREAD

**Issue by abique** [steinbergmedia/vst3_pluginterfaces#2]
https://github.com/steinbergmedia/vst3_pluginterfaces/blob/de91bf4199959f9496cf6d14990fce037435ade5/gui/iplugview.h#L224

Hi,
This is likely being called back after a select/poll/epoll reactor.
Ideally it should also specify if the fd is ready for read/write, so we can save a poll() to get that information.
Alex.

**Comment by abique** [comment]
Also I would suggest an other name for the method:

onFdEvent(int fd, int eventMask)

where eventMask would tell you if there is input available, output can be written, disconnection or error.
You can check poll or epoll.

**Comment by abique** [comment]
Forget about this one.

**Comment by abique** [comment]
I re-open because this interface needs to be either simplified or more advanced:
 - simplified, if it only notifies when you can read
 - advanced, it should then be more analogue to epoll, where you can enable/disable notify flags, because if you have a fd and you don't want to write but write is always available then you'll have a lot of notifications "write available".

**Comment by scheffle** [comment]
Can you give me a use case where you register a file descriptor for event handling where the communication is not bidirectional ?
Only notifying about readability did not work with GTK.

**Comment by abique** [comment]
If you register an fd from epoll_create(), you only need the read I think and then you can have your own fd reactor.

Usually you turn off events for writing and only when you want to write something you first try to write and if you received EWOULDBLOCK then you activate the write event and wait for it to write. If write is always on, then your polling mechanism will always return to tell you "write is ready" even if you don't have anything to write.

Is that correct?

**Comment by scheffle** [comment]
OK, I just rechecked, and there's a bug in the example host which lead me to the conclusion that a notification of writability is needed, but that is not the case. So we will change the documentation that only readability will be notified.

**Comment by abique** [comment]
OK Very good, thanks :)

Then I'll implement it as specified in the next days.
