### ISSUE TITLE
registerTimer on Linux is not essential

### ISSUE THREAD

**Issue by abique** [steinbergmedia/vst3_pluginterfaces#3]
https://github.com/steinbergmedia/vst3_pluginterfaces/blob/de91bf4199959f9496cf6d14990fce037435ade5/gui/iplugview.h#L267

Hi,

I think this one is not essential, because if you can register a FD, then you can use timerfd_create() and register it.

The only advantage that I can see is to have a sorted queue of timers and use the poll() timeout to trigger those events, but I'm not sure that it would be supperior to the timerfd api.

Alex.

**Comment by scheffle** [comment]
Hi Alex,
the disadvantage of using timerfd_create is that this is a linux only API, while the current interface can also be used on any other unix like system. The host is free to use timerfd_create to handle plug-in timers.

Arne

**Comment by abique** [comment]
So far this interface is Linux only right? That's what I understand from the header.

**Comment by scheffle** [comment]
Currently we only support linux, but we could adopt this for BSD Unix fairly easy this way.

**Comment by abique** [comment]
OK.

**Comment by abique** [comment]
What about splitting it from the FD reactor?

**Comment by scheffle** [comment]
I think they belong to each other. It's all about event handling.
