### ISSUE TITLE
We need an additional enum entry for tresult

### ISSUE THREAD

**Issue by abique** [steinbergmedia/vst3_pluginterfaces#4]
Hi,

I've thought that it would be convenient to have a kInvalidThread, because I want to check for example that all the GUI calls happends on the main thread and just discard those which happens on an other thread with return kInvalidThread.

What do you think?

Alex.

**Comment by scheffle** [comment]
I don't think that this is a good way to handle this. I would just call std::terminate (), because this may be a fatal error and silently continuing would cover up the real issue.

**Comment by abique** [comment]
Fair enough :)
This one can be closed as well ;-)
