### ISSUE TITLE
Use C11's _Alignas instead of #pragma pack

### ISSUE THREAD

**Issue by WalterBright** [steinbergmedia/vst3_pluginterfaces#9]
Files like:

https://github.com/steinbergmedia/vst3_pluginterfaces/blob/b8566ef3b2a0cba60a96e3ef2001224c865c8b36/base/falignpush.h

rely on `#pragma pack` which is obsolete.

**Comment by scheffle** [comment]
We still need to support compilers which do not support C11. But we will reconsider this change if we can drop these compilers.

**Comment by WalterBright** [comment]
There's a predefined macro for C11 which can be used to provide an alternate path to support obsolete compilers.
